add_library(common)

target_sources(common
    PRIVATE
        2dShapes/shapes.cpp
        linalg/vec3.cpp
        linalg/mat3.cpp
        core/triangle.cpp
        core/color.cpp
        core/ray.h
        core/camera.cpp
        core/mesh.cpp
        core/scene.cpp
        core/material.cpp
        core/baryCoord.h
        core/intersectionData.h
        core/light.cpp
        core/aabb.h
        shader/diffuseShader.cpp
        shader/refractiveShader.cpp
        shader/reflectiveShader.cpp
        shader/constantShader.cpp
        shader/recursiveShader.cpp
        util/transform.h
        util/renderPPM.h
        texture/texture.h
        texture/albedoTexture.h
        texture/bitmapTexture.h
        texture/checkerTexture.h
        texture/edgeTexture.h
)

target_include_directories(common
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/2dShapes
        ${CMAKE_CURRENT_SOURCE_DIR}/core
        ${CMAKE_CURRENT_SOURCE_DIR}/linalg
        ${CMAKE_CURRENT_SOURCE_DIR}/util
        ${CMAKE_CURRENT_SOURCE_DIR}/rapidjson
        ${CMAKE_CURRENT_SOURCE_DIR}/shader
        ${CMAKE_CURRENT_SOURCE_DIR}/texture
        ${CMAKE_CURRENT_SOURCE_DIR}/stb_image
)
